# Generated by Django 4.0.1 on 2022-02-10 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='vatiation_category',
            new_name='variation_category',
        ),
    ]
