# Generated by Django 4.0.1 on 2022-02-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='has_perm',
        ),
    ]
